[package]
name = "cmakefmt_web"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
anyhow = "1.0.79"
cmakefmt = { version = "*", path = ".." }
wasm-bindgen = "0.2.89"